# Generated by Django 5.2.8 on 2025-11-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_job_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
