# Generated by Django 5.2.8 on 2025-11-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_remove_candidate_notes_resume_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='parsed_data',
        ),
    ]
