# Generated by Django 5.2.8 on 2025-11-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_remove_resume_parsed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
