# Generated by Django 5.2.8 on 2025-12-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_resume_parsed_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_text',
        ),
    ]
