# Generated by Django 5.2.8 on 2025-11-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='sequence_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smsmessages',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('received', 'Received'), ('delivered', 'Delivered'), ('failed', 'Failed')], max_length=50),
        ),
    ]
