# Generated by Django 5.2.8 on 2025-11-18 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_remove_candidate_notes_resume_job_and_more'),
        ('interviews', '0002_interviewquestion_sequence_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='export_file_path',
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interview'),
        ),
    ]
