# Generated by Django 5.2.8 on 2025-11-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_remove_interview_export_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
